version: "3.9"

services:
  devopsdb:
    image: sgsk5137/dbimage:automation
    ports:
      - "3306:3306"
    networks:
      - app_network
    volumes:
      - db_vol:/var/lib/mysql
      
  application:
    image: sgsk5137/appimage:automation
    ports:
      - "2222:8080"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 512M  
    depends_on:
      - devopsdb
    networks:
      - app_network

networks:
  app_network:
    driver: overlay
volumes:
  db_vol:
